---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-sts
  name: test-sts
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: container-1-web-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-sts
  sessionAffinity: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: test-sts
  name: test-sts
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-sts
  serviceName: test-sts
  template:
    metadata:
      labels:
        app: test-sts
    spec:
      affinity: {}
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: LANG
          value: C.UTF-8
        image: registry.cn-beijing.aliyuncs.com/dotbalo/busybox:1.28 
        command: [ "sleep", "1000000" ]
        imagePullPolicy: Always
        lifecycle: {}
        name: test-sts
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /mnt
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        limits:
          storage: 2Gi
        requests:
          storage: 1Gi
      storageClassName: csi-hostpath-sc 
