  
kind: Service
apiVersion: v1
metadata:
  name: csi-hostpath-snapshotter
  labels:
    app: csi-hostpath-snapshotter
spec:
  selector:
    app: csi-hostpath-snapshotter
  ports:
    - name: dummy
      port: 12345
